name = "quasi-borel-spaces"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["QuasiBorelSpaces"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.missingDocs = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.0-rc2"

[[require]]
name = "rose-tree"
git = "https://github.com/YellPika/lean-rose-tree"
rev = "main"

[[lean_lib]]
name = "QuasiBorelSpaces"
